export type CreateInventoryDto = {
  orderId: number;
  code?: string;
  name?: string;
  category?: string;
  material?: string;
  karat?: string;
  goldType?: string;
  goldColor?: string;
  weightGross?: number;
  weightNet?: number;
  stoneCount?: number;
  stoneWeight?: number;
  size?: string;
  dimensions?: string;
  barcode?: string;
  sku?: string;
  location?: string;
  branchLocation?: 'ASIA' | 'SUN_PLAZA';
  placement?: 'ETALASE' | 'PENYIMPANAN';
  cost?: number;
  price?: number;
  status?: string;
  statusEnum?: 'DRAFT' | 'ACTIVE' | 'RESERVED' | 'SOLD' | 'RETURNED' | 'DAMAGED';
  images?: string[];
  notes?: string;
  stones?: { bentuk: string; jumlah: number; berat?: number }[];
};

export type UpdateInventoryDto = Partial<CreateInventoryDto>;
