version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: sumatra_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sumatra_jewelry
      MYSQL_USER: sumatra
      MYSQL_PASSWORD: sumatra
      # Ensure native auth so Prisma can connect without unknown plugin errors
      MYSQL_TCP_PORT: 3306
    command: [
      "--default_authentication_plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psumatra"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
