-- AlterTable
ALTER TABLE `appuser` MODIFY `job_role` ENUM('ADMINISTRATOR', 'SALES', 'DESIGNER', 'CASTER', 'CARVER', 'DIAMOND_SETTER', 'FINISHER', 'INVENTORY') NULL;

-- AlterTable
ALTER TABLE `ordertask` MODIFY `job_role` ENUM('ADMINISTRATOR', 'SALES', 'DESIGNER', 'CASTER', 'CARVER', 'DIAMOND_SETTER', 'FINISHER', 'INVENTORY') NULL;
